### ISSUE TITLE
redislabs/redisai gpu docker images not working 

### ISSUE THREAD

**Issue by samuelkees** [RedisAI/RedisAI#835] opened 2021-08-23 06:12 UTC
**Describe the bug**
I get this error when i try to run a edge-gpu docker image:
`docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "--loadmodule": executable file not found in $PATH: unknown.`

**To Reproduce**
1. run `sudo docker run -p 6379:6379 -it --rm redislabs/redisai:edge-gpu-xenial`

**Expected behavior**
RedisAi starts as RedisAi does before when i used `docker run -p 6379:6379 --gpus all -it --rm redislabs/redisai:edge-gpu` witch is not working because its not in docker hub anymore `'redislabs/redisai:edge-gpu not found: manifest unknown'`

**Environment (please complete the following information):**
 - OS: mint 20.2 / ubuntu 20.04
 - Version 1.2.4
 - Platfrom x86_64
 - Runtime CUDA (GPU)

**Additional context**
by the way: `docker run -p 6379:6379 --gpus all -it --rm redislabs/redisai:edge-gpu` is the recommended command in the readme of this repo.

**Comment by samuelkees** [comment] 2021-08-25 06:03
Hello thank you for the fast response. Unfortunately i still have the same error. In the commit 5a384c7689534efaf761fb21a4e025c638fca7ec the command ```CMD ["--loadmodule", "/usr/lib/redis/modules/redisai.so"]``` was changed to `CMD ["/usr/local/bin/redis-server", "--loadmodule", "/usr/lib/redis/modules/redisai.so"]` but in the docker image released after the merge the last command is still `CMD ["--loadmodule" "/usr/lib/redis/modules/redisai.so"]` ([ docker hub](https://hub.docker.com/layers/redislabs/redisai/edge-gpu-xenial/images/sha256-d5e06f4cf1cdcc4ebc92a403d3d12b1b48397c7eca8aecde36d806be64f3d951?context=explore)). 

I'm not sure if this is the problem. By the way i really like RedisAi! Thank you all for the good job!

**Comment by chayim** [comment] 2021-08-25 06:27
@samuelkees I'll spin it locally and validate. The generator *should* have done the right there since in a local test it seemed sane.

**Comment by chayim** [comment] 2021-08-25 07:39
@samuelkeesThe issue is that the docker never pushed upstream since there's (my) bug in the template.  I just built locally from the master I'm
```
<snip>
Step 40/43 : COPY --from=redis /usr/local/bin/* /usr/local/bin/
---> Using cache
---> f0eb848bb628
Step 41/43 : WORKDIR /data
---> Using cache
---> 56a7282234f7
Step 42/43 : EXPOSE 6379
---> Using cache
---> 7649a5925196
Step 43/43 : CMD ["/usr/local/bin/redis-server", "--loadmodule", "/usr/lib/redis/modules/redisai.so"]
---> Using cache
---> 62b5c281555e
Successfully built 62b5c281555e
Successfully tagged redislabs/redisai:edge-gpu-bionic
ubuntu@ip-172-31-30-181:~/depos/redisai/opt/build/docker$ ^C
ubuntu@ip-172-31-30-181:~/depos/redisai/opt/build/docker$ docker run -it redislabs/redisai:edge-gpu-bionic 
1:C 25 Aug 2021 07:26:39.389 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 25 Aug 2021 07:26:39.389 # Redis version=6.2.5, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 25 Aug 2021 07:26:39.389 # Configuration loaded
1:M 25 Aug 2021 07:26:39.389 * monotonic clock: POSIX clock_gettime
                _._                                                  
           _.-``__ ''-._                                             
      _.-``    `.  `_.  ''-._           Redis 6.2.5 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._                                  
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 1
  `-._    `-._  `-./  _.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |           https://redis.io       
  `-._    `-._`-.__.-'_.-'    _.-'                                   
 |`-._`-._    `-.__.-'    _.-'_.-'|                                  
 |    `-._`-._        _.-'_.-'    |                                  
  `-._    `-._`-.__.-'_.-'    _.-'                                   
      `-._    `-.__.-'    _.-'                                       
          `-._        _.-'                                           
              `-.__.-'                                               

1:M 25 Aug 2021 07:26:39.390 # Server initialized
1:M 25 Aug 2021 07:26:39.390 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 25 Aug 2021 07:26:39.390 * <ai> Redis version found by RedisAI: 6.2.5 - oss
1:M 25 Aug 2021 07:26:39.390 * <ai> RedisAI version 999999, git_sha=314a83bf10e922c19193e46d71f32a520679bd6d
1:M 25 Aug 2021 07:26:39.390 * Module 'ai' loaded from /usr/lib/redis/modules/redisai.so
1:M 25 Aug 2021 07:26:39.391 * Ready to accept connections
```

So your options are:

1. Wait for my incoming PR to land in master, and a docker should end up upstream (hopefully by the time you read this!)
2. Clone master with a git clone --recursive, and assuming you have a valid docker universe: cd <REPO>/opt/build/docker && make GPU=1. You'll get a docker image locally tagged as **redislabs/redisai:edge-gpu-bionic** that you can use via:
    docker run -p 6379:6379 -it redislabs/redisai:edge-gpu-bionic


I'm leaving this open, purely to watch CI. If this is closed by the time you read this, CI passed.

**Comment by samuelkees** [comment] 2021-08-25 09:15
hey thank you it works!

**Comment by chayim** [comment] 2021-08-25 09:37
Awesome... Now to fix a variant you're not using but we are. Enjoy!

**Closed** 2021-08-25 09:57 UTC
