### ISSUE TITLE
potential leak on redis createEmbeddedStringObject ( needs further investigation )

### ISSUE THREAD

**Issue by filipecosta90** [RedisAI/RedisAI#298] opened 2020-02-23 20:01 UTC
this a leak that appears multiple times on our tests and it can be either a missuse in our side or a real leak on redis. We should investigate further prior that creating an issue on redis himself. 

example test that only has this leak:

```make -C opt test GEN=0 SLAVES=0 AOF=0 VALGRIND=1 TEST="tests_tensorflow.py\:test_tensorflow_modelinfo"```

```
==8556== 168 bytes in 8 blocks are definitely lost in loss record 107,399 of 114,486
==8556==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==8556==    by 0x144D38: zmalloc (zmalloc.c:99)
==8556==    by 0x1531CF: createEmbeddedStringObject (object.c:85)
==8556==    by 0x15332B: createStringObject (object.c:121)
==8556==    by 0x14EEA9: processMultibulkBuffer (networking.c:1405)
==8556==    by 0x14F02E: processInputBuffer (networking.c:1460)
==8556==    by 0x14F1DB: processInputBufferAndReplicate (networking.c:1505)
==8556==    by 0x14F551: readQueryFromClient (networking.c:1587)
==8556==    by 0x1342E2: aeProcessEvents (ae.c:443)
==8556==    by 0x1344FC: aeMain (ae.c:501)
==8556==    by 0x141FD3: main (server.c:4234)

```

**Comment by lantiga** [comment] 2020-02-29 16:10
Can't reproduce on my system (Ubuntu via Docker on macOS)

**Comment by lantiga** [comment] 2020-03-05 21:01
I can't reproduce in Redis on the 6.0 branch on Ubuntu. Closing for now, @filipecosta90 feel free to reopen.

**Closed by lantiga** 2020-03-05 21:01 UTC
Labels: investigating
