### ISSUE TITLE
YOLO Inference takes 5 seconds on averagae

### ISSUE THREAD

**Issue by srijiths** [RedisAI/RedisAI#119] opened 2019-05-13 09:01 UTC
Hi All,

I have tried YOLO inference using redisai-python client. The inference time i am getting is very high. What would be the guidelines and suggestions to make RedisAI in production.

````
1:M 13 May 2019 07:44:19.480 * <ai> RAI_ModelRun took 4.966000s
1:M 13 May 2019 07:44:50.500 * <ai> RAI_ModelRun took 5.858000s
1:M 13 May 2019 07:45:22.227 * <ai> RAI_ModelRun took 5.798000s
1:M 13 May 2019 08:47:34.765 * <ai> RAI_ModelRun took 5.604000s
1:M 13 May 2019 08:47:56.107 * <ai> RAI_ModelRun took 5.912000s
1:M 13 May 2019 08:48:05.820 * <ai> RAI_ModelRun took 5.627000s
1:M 13 May 2019 08:48:16.238 * <ai> RAI_ModelRun took 5.682000s
````
Reproduction Steps:
Python program available at https://gist.github.com/srijiths/94b23ef3b1b3650d819dbfd917d37d28
Above program is collated from this blog https://medium.com/tensorwerk/redisai-thors-stormbreaker-for-deep-learning-deployment-a3fe7569c559

Regards,
Srijith

**Comment by hhsecond** [comment] 2019-05-13 12:33
@srijiths The timing looks like the first time run of your model after the model is set (`MODELSET`). On the first run, the model initializing operations causes the run to be slower. Normally, in production, we set the model and only the first run on the model will be delayed. Can you try executing `MODELSET` & `SCRIPTSET` separately and then execute other parts of the code (ignore the first run though)

**Comment by srijiths** [comment] 2019-05-13 12:49
@hhsecond I have separated model set and inference part. Now from 5 Sec it has been reduces to 2 Sec on average. Output below
```
1:M 13 May 2019 12:41:16.133 * <ai> RAI_ModelRun took 6.956000s
1:M 13 May 2019 12:41:17.737 * <ai> RAI_ModelRun took 1.566000s
1:M 13 May 2019 12:41:19.709 * <ai> RAI_ModelRun took 1.937000s
1:M 13 May 2019 12:41:21.704 * <ai> RAI_ModelRun took 1.966000s
1:M 13 May 2019 12:41:23.656 * <ai> RAI_ModelRun took 1.920000s
1:M 13 May 2019 12:41:25.644 * <ai> RAI_ModelRun took 1.959000s
1:M 13 May 2019 12:41:27.621 * <ai> RAI_ModelRun took 1.943000s
1:M 13 May 2019 12:41:29.595 * <ai> RAI_ModelRun took 1.943000s
1:M 13 May 2019 12:41:31.582 * <ai> RAI_ModelRun took 1.954000s
1:M 13 May 2019 12:41:33.546 * <ai> RAI_ModelRun took 1.935000s
1:M 13 May 2019 12:41:35.526 * <ai> RAI_ModelRun took 1.951000s
1:M 13 May 2019 12:41:37.492 * <ai> RAI_ModelRun took 1.938000s
1:M 13 May 2019 12:41:39.450 * <ai> RAI_ModelRun took 1.927000s
1:M 13 May 2019 12:41:41.742 * <ai> RAI_ModelRun took 2.264000s
1:M 13 May 2019 12:41:44.071 * <ai> RAI_ModelRun took 2.272000s
1:M 13 May 2019 12:41:46.440 * <ai> RAI_ModelRun took 2.328000s
1:M 13 May 2019 12:41:48.791 * <ai> RAI_ModelRun took 2.306000s
1:M 13 May 2019 12:41:51.013 * <ai> RAI_ModelRun took 2.189000s
1:M 13 May 2019 12:41:52.997 * <ai> RAI_ModelRun took 1.953000s
``
But there is one thing which i noticed is even if i specify "rai.Device.gpu" in con.modelset, its not running in GPU. Other than this setting any thing else to be done to run it in GPU ?

Thank You,
Srijith

**Comment by hhsecond** [comment] 2019-05-13 13:47
Ok, I have to check the Device thing. Do you mind sharing the latest code here? We were able to run it in less than 300ms on CPU.

**Comment by srijiths** [comment] 2019-05-13 14:31
@hhsecond code used is here in gist https://gist.github.com/srijiths/94b23ef3b1b3650d819dbfd917d37d28

**Comment by srijiths** [comment] 2019-05-13 16:02
@hhsecond I assume that below statement is costly operation. Took below statements out of the loop and made it initialize only once made significant difference. Now its coming as per your results as well. On average 300+ ms

gist updated : https://gist.github.com/srijiths/94b23ef3b1b3650d819dbfd917d37d28

```
input_shape = rai.Tensor(rai.DType.float, shape=[2], value=[new_shape, new_shape])
con.tensorset('input_shape', input_shape)
```
```
1:M 13 May 2019 15:57:52.203 * <ai> RAI_ModelRun took 0.379000s
1:M 13 May 2019 15:57:54.136 * <ai> RAI_ModelRun took 1.888000s
1:M 13 May 2019 15:57:54.505 * <ai> RAI_ModelRun took 0.326000s
1:M 13 May 2019 15:57:54.881 * <ai> RAI_ModelRun took 0.337000s
1:M 13 May 2019 15:57:55.265 * <ai> RAI_ModelRun took 0.340000s
1:M 13 May 2019 15:57:55.640 * <ai> RAI_ModelRun took 0.328000s
1:M 13 May 2019 15:57:56.020 * <ai> RAI_ModelRun took 0.329000s
1:M 13 May 2019 15:57:56.393 * <ai> RAI_ModelRun took 0.335000s
1:M 13 May 2019 15:57:56.796 * <ai> RAI_ModelRun took 0.360000s
1:M 13 May 2019 15:57:57.169 * <ai> RAI_ModelRun took 0.337000s
1:M 13 May 2019 15:57:57.545 * <ai> RAI_ModelRun took 0.338000s
1:M 13 May 2019 15:57:57.918 * <ai> RAI_ModelRun took 0.337000s
1:M 13 May 2019 15:57:58.290 * <ai> RAI_ModelRun took 0.328000s
1:M 13 May 2019 15:57:58.687 * <ai> RAI_ModelRun took 0.350000s
1:M 13 May 2019 15:57:59.109 * <ai> RAI_ModelRun took 0.379000s
1:M 13 May 2019 15:58:01.052 * <ai> RAI_ModelRun took 1.885000s
1:M 13 May 2019 15:58:01.472 * <ai> RAI_ModelRun took 0.381000s
1:M 13 May 2019 15:58:01.840 * <ai> RAI_ModelRun took 0.326000s
1:M 13 May 2019 15:58:02.249 * <ai> RAI_ModelRun took 0.368000s
1:M 13 May 2019 15:58:02.689 * <ai> RAI_ModelRun took 0.397000s
1:M 13 May 2019 15:58:03.111 * <ai> RAI_ModelRun took 0.386000s
1:M 13 May 2019 15:58:03.491 * <ai> RAI_ModelRun took 0.341000s
1:M 13 May 2019 15:58:03.852 * <ai> RAI_ModelRun took 0.321000s
1:M 13 May 2019 15:58:04.240 * <ai> RAI_ModelRun took 0.347000s
1:M 13 May 2019 15:58:06.074 * <ai> RAI_ModelRun took 1.790000s
1:M 13 May 2019 15:58:06.496 * <ai> RAI_ModelRun took 0.383000s
1:M 13 May 2019 15:58:08.434 * <ai> RAI_ModelRun took 1.898000s
1:M 13 May 2019 15:58:08.877 * <ai> RAI_ModelRun took 0.405000s
1:M 13 May 2019 15:58:09.306 * <ai> RAI_ModelRun took 0.385000s
1:M 13 May 2019 15:58:09.718 * <ai> RAI_ModelRun took 0.371000s
1:M 13 May 2019 15:58:10.122 * <ai> RAI_ModelRun took 0.364000s
1:M 13 May 2019 15:58:10.509 * <ai> RAI_ModelRun took 0.345000s
1:M 13 May 2019 15:58:10.879 * <ai> RAI_ModelRun took 0.335000s
1:M 13 May 2019 15:58:11.290 * <ai> RAI_ModelRun took 0.363000s
1:M 13 May 2019 15:58:11.692 * <ai> RAI_ModelRun took 0.364000s
1:M 13 May 2019 15:58:12.088 * <ai> RAI_ModelRun took 0.357000s
1:M 13 May 2019 15:58:12.497 * <ai> RAI_ModelRun took 0.371000s
1:M 13 May 2019 15:58:12.884 * <ai> RAI_ModelRun took 0.342000s
1:M 13 May 2019 15:58:13.262 * <ai> RAI_ModelRun took 0.339000s
1:M 13 May 2019 15:58:13.636 * <ai> RAI_ModelRun took 0.335000s
1:M 13 May 2019 15:58:14.006 * <ai> RAI_ModelRun took 0.329000s
1:M 13 May 2019 15:58:15.888 * <ai> RAI_ModelRun took 1.839000s
1:M 13 May 2019 15:58:16.443 * <ai> RAI_ModelRun took 0.515000s
1:M 13 May 2019 15:58:16.842 * <ai> RAI_ModelRun took 0.361000s
1:M 13 May 2019 15:58:17.243 * <ai> RAI_ModelRun took 0.362000s
1:M 13 May 2019 15:58:17.622 * <ai> RAI_ModelRun took 0.343000s
1:M 13 May 2019 15:58:17.999 * <ai> RAI_ModelRun took 0.331000s
1:M 13 May 2019 15:58:19.929 * <ai> RAI_ModelRun took 1.893000s
1:M 13 May 2019 15:58:20.301 * <ai> RAI_ModelRun took 0.333000s
1:M 13 May 2019 15:58:20.665 * <ai> RAI_ModelRun took 0.322000s
1:M 13 May 2019 15:58:21.068 * <ai> RAI_ModelRun took 0.365000s
1:M 13 May 2019 15:58:21.440 * <ai> RAI_ModelRun took 0.322000s
1:M 13 May 2019 15:58:21.806 * <ai> RAI_ModelRun took 0.317000s
1:M 13 May 2019 15:58:22.221 * <ai> RAI_ModelRun took 0.373000s
1:M 13 May 2019 15:58:22.623 * <ai> RAI_ModelRun took 0.355000s
1:M 13 May 2019 15:58:23.006 * <ai> RAI_ModelRun took 0.341000s
1:M 13 May 2019 15:58:23.365 * <ai> RAI_ModelRun took 0.320000s
1:M 13 May 2019 15:58:23.763 * <ai> RAI_ModelRun took 0.355000s
1:M 13 May 2019 15:58:24.118 * <ai> RAI_ModelRun took 0.314000s
1:M 13 May 2019 15:58:24.482 * <ai> RAI_ModelRun took 0.321000s
1:M 13 May 2019 15:58:24.863 * <ai> RAI_ModelRun took 0.343000s
1:M 13 May 2019 15:58:25.253 * <ai> RAI_ModelRun took 0.348000s
1:M 13 May 2019 15:58:25.624 * <ai> RAI_ModelRun took 0.331000s
1:M 13 May 2019 15:58:27.643 * <ai> RAI_ModelRun took 1.975000s
1:M 13 May 2019 15:58:28.046 * <ai> RAI_ModelRun took 0.365000s
1:M 13 May 2019 15:58:28.416 * <ai> RAI_ModelRun took 0.327000s
1:M 13 May 2019 15:58:28.811 * <ai> RAI_ModelRun took 0.351000s
1:M 13 May 2019 15:58:29.194 * <ai> RAI_ModelRun took 0.338000s
1:M 13 May 2019 15:58:29.575 * <ai> RAI_ModelRun took 0.337000s
1:M 13 May 2019 15:58:29.963 * <ai> RAI_ModelRun took 0.351000s
1:M 13 May 2019 15:58:30.333 * <ai> RAI_ModelRun took 0.333000s
1:M 13 May 2019 15:58:30.706 * <ai> RAI_ModelRun took 0.331000s
1:M 13 May 2019 15:58:31.081 * <ai> RAI_ModelRun took 0.333000s
1:M 13 May 2019 15:58:31.439 * <ai> RAI_ModelRun took 0.322000s
1:M 13 May 2019 15:58:31.817 * <ai> RAI_ModelRun took 0.331000s
1:M 13 May 2019 15:58:32.174 * <ai> RAI_ModelRun took 0.319000s
1:M 13 May 2019 15:58:32.549 * <ai> RAI_ModelRun took 0.335000s
1:M 13 May 2019 15:58:32.904 * <ai> RAI_ModelRun took 0.314000s
1:M 13 May 2019 15:58:33.271 * <ai> RAI_ModelRun took 0.330000s
1:M 13 May 2019 15:58:35.099 * <ai> RAI_ModelRun took 1.781000s
1:M 13 May 2019 15:58:35.523 * <ai> RAI_ModelRun took 0.382000s
1:M 13 May 2019 15:58:37.379 * <ai> RAI_ModelRun took 1.812000s
1:M 13 May 2019 15:58:37.796 * <ai> RAI_ModelRun took 0.373000s
1:M 13 May 2019 15:58:39.402 * <ai> RAI_ModelRun took 1.564000s
1:M 13 May 2019 15:58:40.022 * <ai> RAI_ModelRun took 0.579000s
1:M 13 May 2019 15:58:40.402 * <ai> RAI_ModelRun took 0.335000s
1:M 13 May 2019 15:58:42.158 * <ai> RAI_ModelRun took 1.717000s
1:M 13 May 2019 15:58:42.711 * <ai> RAI_ModelRun took 0.510000s
1:M 13 May 2019 15:58:43.119 * <ai> RAI_ModelRun took 0.363000s
1:M 13 May 2019 15:58:43.497 * <ai> RAI_ModelRun took 0.338000s
1:M 13 May 2019 15:58:43.889 * <ai> RAI_ModelRun took 0.349000s
1:M 13 May 2019 15:58:44.559 * <ai> RAI_ModelRun took 0.622000s
1:M 13 May 2019 15:58:46.365 * <ai> RAI_ModelRun took 1.764000s
1:M 13 May 2019 15:58:46.736 * <ai> RAI_ModelRun took 0.330000s
1:M 13 May 2019 15:58:47.130 * <ai> RAI_ModelRun took 0.352000s
```
Still not recognizing GPU is there. Please let me know if you found something.

Thank You,
Srijith

**Comment by hhsecond** [comment] 2019-05-14 05:38
The spikes in the timings are still concerning. For confirming my suspicion: How did you install dependencies while building RedisAI
`bash get_deps.sh cpu` or `bash get_deps.sh` or are you using docker?

**Comment by srijiths** [comment] 2019-05-14 06:13
i am using redisai/redisai docker Sherin.

**Comment by srijiths** [comment] 2019-05-14 06:17
@hhsecond In redisai docker published in docker hub always build on CPU. See this line.
```
RUN set -ex;\
    mkdir -p deps;\
    DEPS_DIRECTORY=deps bash ./get_deps.sh cpu
```
I will change this to GPU and see the results.

**Comment by hhsecond** [comment] 2019-05-14 06:23
Right, so there are two things you could do to improve performance.
1. Build with GPU
2. Build TF with optimizations on for CPU users

I'll try to push the GPU build to docker hub soon. Thanks for pointing this out.

**Comment by lantiga** [comment] 2019-06-11 22:05
@hhsecond what needs to be done to finally close this?

**Comment by lantiga** [comment] 2019-06-28 11:55
Dependent on activity in #120. Roadmap is to run all tests on GPU on CI.

**Comment by hhsecond** [comment] 2019-08-28 07:49
@srijiths There were a lot of improvements made to the core in the past weeks/months. With all those, I couldn't reproduce this issue anymore. On an RTX 2070, I could get 0.025 to 0.08 seconds for each 'modelrun' (timed from python, so it includes the roundtrip time between client & RedisAI as well). I am going to close this issue for now.
Also, We have the GPU RedisAI containerized with docker ready (README is updated). Feel free to take a look and reopen this issue if it is not solved for you yet

**Closed by hhsecond** 2019-08-28 07:49 UTC
Labels: performance
